services:

  
  auth-service:
    build: ./auth-service
    ports:
      - "5010:5001"
    depends_on:
      - mongo
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=supersecret123

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5020:5002"
    depends_on:
      - mongo
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/restaurant-db
      - JWT_SECRET=supersecret123

  order-service:
    build: ./order-service
    ports:
      - "5030:5003"
    depends_on:
      - mongo
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongo:27017/order-db
      - JWT_SECRET=supersecret123

  delivery-service:
    build: ./delivery-service
    ports:
      - "5040:5004"
    depends_on:
      - order-service
    environment:
      - PORT=5004
      - ORDER_SERVICE_URL=http://order-service:5003
      - JWT_SECRET=supersecret123

  notification-service:
    build: ./notification-service
    ports:
      - "5060:5006"
    environment:
      - PORT=5006
      - TWILIO_ACCOUNT_SID=AC8db00a13d0f006050d9d6996e3625120
      - TWILIO_AUTH_TOKEN=79c5d5e212b4b7576bd10c9122fd27b3
      - TWILIO_PHONE=+94 766364158
      - EMAIL_FROM=sachithkavishka0001@gmail.com
      - EMAIL_PASS=ghtn egyw ejsk boqf

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  # frontend:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
